name: ESLint
on:
  pull_request:
    branches: [master, next, next-major, beta, alpha, '[0-9]+.x']
jobs:
  es-lint:
      name: ESLint
      runs-on: ubuntu-latest
      steps:
      - uses: actions/checkout@v4
      - name: Install dependencies
        run: npm ci
      - name: Run ESLint
        run: npm run lint
