name: Package size report

on:
  pull_request:
    branches: [master, next, next-major, beta, alpha, '[0-9]+.x']
jobs:
  pkg-size-report:
    name: Package size report
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version-file: ".nvmrc"
      - name: Package size report
        uses: pkg-size/action@develop
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          hide-files: '*.{js,css}.map'
