name: Test
on:
  pull_request:
    branches: [master, next, next-major, beta, alpha, '[0-9]+.x']
jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version-file: ".nvmrc"
      - name: Install dependencies
        run: npm ci
      - name: Test
        run: npm run test
      - name: Coverage
        run: npm run coverage:ci
      - name: Make coverage badges
        run: npm run make-coverage-badges:ci
